# Generated by Django 5.2.6 on 2025-09-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
