# Generated by Django 5.2.6 on 2025-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='imagem_referencia_1',
            field=models.ImageField(blank=True, null=True, upload_to='encomendas/referencias/', verbose_name='Imagem de Referência 1'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='imagem_referencia_2',
            field=models.ImageField(blank=True, null=True, upload_to='encomendas/referencias/', verbose_name='Imagem de Referência 2'),
        ),
    ]
