# Generated by Django 5.2.6 on 2025-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
    ]
